### ISSUE TITLE
[Request]Delete the old version of workflow

### ISSUE THREAD

**Issue by owenwater** [hzlzh/AlfredWorkflow.com#25]
Hi hzlzh,

I used `way 2` in #6 to update my workflow. Please delete my old one.(name: Calendar, version: 1.0, author: owenwater)

BTW, I tried `way 1` but looks like the repo hasn't been updated for a long time so my workflow does not exist in the source code.

Regards,
Owen

**Comment by hzlzh** [comment]
@owenwater Thanks for your note, I'll update them now.

**Comment by owenwater** [comment]
hi @hzlzh 

I'm so sorry but I have to ask you to do the same thing again because I just fixed a bug in my workflow.

BTW, I'm just curious about why not a `update page` but `pull request` which has lots of things need to be done manually. For example, a workflow has same name, bundle id and author name may replace the previous one. Or using email verification because of the security issue.

Regards,
Owen

**Comment by hzlzh** [comment]
Your workflow is now updated :)

 `pull request` way would be better if every workflow developers can provide a GitHub download link instead of the download link from the website, even a small change which they made in their workflow can take effect when a user download it immediately.

For now, I can only hope developers re-upload their workflows and delete the previous one.

Also `email verification` is really a good way, I'll try.

**Comment by owenwater** [comment]
Thanks a lot.

I'm a little confused here. So sending the `pull request` to this repo can only change content for `Download from Github` or `Download from Backup`? For Github link, I do provide one which points to my own repo when submitting the workflow. The things I really want to update is the backup link along with the stuff like version number or screenshot which I even can't find here. Is `new workflow + manually delete the old one` the only way to update these things?

**Comment by hzlzh** [comment]
Yes, It's currently `new workflow + manually delete the old one` on the website.

While a download link from your own repo is a very recommended way to keep the workflow updated all the time.
